# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [pipeline]
  pull_request:
    branches: [pipeline]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        meteor: ["1.8.0"]
        node: ["8.11"]
    name: Meteor ${{ matrix.meteor }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: npm --version
      - run: meteor --version
      - run: meteor npm install
      - run: meteor build --directory ./
      - run: cd bundle
      - run: ls -al
